version: "3.8"

services:
  app:
    build: .
    image: 1c-bitrix24-sync:latest
    container_name: 1c-bitrix24-sync
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    restart: unless-stopped